### ISSUE TITLE
Error al iniciar web app

### ISSUE THREAD

**Issue by devsoftx** [aniversarioperu/ventanita#13]
Ayer intente levantar la web app y obtenia el mensaje:
"SECRET KEY must not be empty" googleando avergigue que en el archivo manage.py en la configuracion habria que agregar ".local " a "ventanita.settings" quedando "ventanita.settings.local"
Así ya me levanto correctamente.
Saludos.

**Comment by aniversarioperu** [comment]
Tienes razón. Falta especificar eso en el README.
También se puede usar el ``Makefile``, la opción ``serve``:

``make serve``

https://github.com/aniversarioperu/ventanita/blob/master/Makefile

``serve:``
``    python ventanita/manage.py runserver --settings=ventanita.settings.local``
