### ISSUE TITLE
instalación de dependencias.

### ISSUE THREAD

**Issue by devsoftx** [aniversarioperu/ventanita#22]
Al instalar la dependencia sudo pip install psycopg2==2.6
Obtengo el siguiente mensaje:
Command python setup.py egg_info failed with error code 1 in /private/tmp/pip_build_root/psycopg2
Storing debug log for failure in /Users/fabricio/Library/Logs/pip.log
PS: Estoy usando una Mac x64, es necesario instalar postgres o alguna herramienta de desarrollo/devkit  de postgres?

**Comment by aniversarioperu** [comment]
pip trata de compilar la libreria psycopg2, entonces necesitas haber instalado los compiladores y posiblemente los headers de python : python-dev

si estas en mac, una opción es que instales el packete compilado http://initd.org/psycopg/docs/install.html#installation




Sent from Samsung tablet

-------- Original message --------
From Fabricio Rojas <notifications@github.com> 
Date: 2015/03/20  05:22  (GMT+02:00) 
To aniversarioperu/ventanita <ventanita@noreply.github.com> 
Subject [ventanita] instalación de dependencias. (#22)

**Comment by devsoftx** [comment]
Ya instalo correctamente
