### ISSUE TITLE
configurar PostgreSQL como nuestra base de datos

### ISSUE THREAD

**Issue by aniversarioperu** [aniversarioperu/ventanita#8]

**Comment by joose2015** [comment]
¿La configuracion debe hacerse en python?

**Comment by aniversarioperu** [comment]
básicamente implica seguir estos pasos https://docs.djangoproject.com/en/1.7/intro/tutorial01/#database-setup

**Comment by aniversarioperu** [comment]
cerrado con 349a2a54a09493e15293bf3c5cc03fa7f4a2eaf8
